version: '2'

services:
  db:
    build: ./postgres
    environment:
      POSTGRES_DB: whereuat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

      WHEREUAT_USERREG_PASS: userreg_secret
      WHEREUAT_APP_PASS: app_secret
    volumes:
      - ./tests:/db/test
      - ./schema:/db/schema
      - ./postgres/test.sh:/test.sh
      - ./postgres/build.sh:/build.sh
